<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Offer Letter - {{ $candidate->full_name }}</title>
    <style>
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11px; color: #333; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 25px; border-bottom: 3px solid #1a56db; padding-bottom: 12px; }
        .header h1 { color: #1a56db; margin: 0; font-size: 22px; }
        .header p { margin: 3px 0; color: #666; font-size: 10px; }
        .date-line { text-align: right; margin-bottom: 20px; }
        .subject { font-weight: bold; font-size: 13px; margin-bottom: 15px; color: #1a56db; }
        .body p { margin: 8px 0; }
        .details-table { width: 100%; border-collapse: collapse; margin: 15px 0; background: #f9fafb; }
        .details-table td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
        .details-table td:first-child { font-weight: bold; color: #4b5563; width: 35%; }
        .signature-section { margin-top: 40px; }
        .signature-box { border-top: 1px solid #333; width: 250px; margin-top: 40px; padding-top: 4px; }
        .footer { margin-top: 30px; font-size: 9px; color: #999; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 10px; }
        ul { margin: 8px 0 8px 20px; padding: 0; }
        li { margin: 3px 0; }
        .badge { background: #dbeafe; color: #1e40af; padding: 3px 10px; border-radius: 12px; font-size: 9px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $company }}</h1>
        <p>35 Centre Road, Morningside, Gauteng, South Africa</p>
        <p>Email: info@nkscapital.co.za | www.nkscapital.co.za</p>
    </div>

    <div class="date-line">
        {{ $generated_at }}
    </div>

    <p><strong>To:</strong> {{ $candidate->full_name }}</p>
    <p><strong>Email:</strong> {{ $candidate->email }}</p>

    <div class="subject">
        RE: Offer of Employment — {{ $position }}
    </div>

    <div class="body">
        <p>Dear {{ $candidate->first_name }},</p>

        <p>
            Following your successful interview process for the position of
            <strong>{{ $position }}</strong> in the <strong>{{ $department }}</strong> department,
            we are pleased to extend to you an offer of employment with {{ $company }}.
        </p>

        <p><strong>Offer Details:</strong></p>

        <table class="details-table">
            <tr>
                <td>Position</td>
                <td>{{ $position }}</td>
            </tr>
            <tr>
                <td>Department</td>
                <td>{{ $department }}</td>
            </tr>
            @if($contract_type)
            <tr>
                <td>Contract Type</td>
                <td>{{ ucfirst(str_replace('_', ' ', $contract_type)) }}</td>
            </tr>
            @endif
            <tr>
                <td>Annual Salary</td>
                <td>R {{ number_format($salary, 2) }} ({{ $requisition->salary_currency ?? 'ZAR' }})</td>
            </tr>
            <tr>
                <td>Start Date</td>
                <td>{{ \Carbon\Carbon::parse($start_date)->format('d F Y') }}</td>
            </tr>
            <tr>
                <td>Notice Period</td>
                <td>{{ $notice_period_days }} days</td>
            </tr>
            <tr>
                <td>Offer Expiry</td>
                <td>{{ \Carbon\Carbon::parse($expiry_date)->format('d F Y') }}</td>
            </tr>
        </table>

        @if(!empty($benefits))
        <p><strong>Benefits:</strong></p>
        <ul>
            @foreach($benefits as $benefit)
                <li>{{ is_array($benefit) ? ($benefit['name'] ?? json_encode($benefit)) : $benefit }}</li>
            @endforeach
        </ul>
        @endif

        <p>
            This offer is subject to the satisfactory completion of our standard pre-employment checks
            and the signing of the employment contract.
        </p>

        <p>
            Please confirm your acceptance of this offer by signing and returning a copy of this letter
            before <strong>{{ \Carbon\Carbon::parse($expiry_date)->format('d F Y') }}</strong>.
        </p>

        <p>
            We look forward to welcoming you to our team.
        </p>
    </div>

    <div class="signature-section">
        <p>Yours sincerely,</p>
        <div class="signature-box">
            <p>Authorised Signatory</p>
            <p>{{ $company }}</p>
        </div>
    </div>

    <div class="footer">
        <p>This offer letter was digitally generated by NKS Capital EMS on {{ $generated_at }}.</p>
    </div>
</body>
</html>