<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Timesheet - {{ $timesheet->month_year->format('F Y') }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #1a56db; padding-bottom: 10px; }
        .header h1 { color: #1a56db; margin: 0; font-size: 20px; }
        .header p { margin: 4px 0; color: #666; }
        .client-info { margin-bottom: 20px; background: #f3f4f6; padding: 10px; border-radius: 4px; }
        .client-info table { width: 100%; }
        .client-info td { padding: 3px 8px; }
        .timesheet-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        .timesheet-table th { background: #1a56db; color: white; padding: 8px; text-align: left; font-size: 10px; text-transform: uppercase; }
        .timesheet-table td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
        .timesheet-table tr:nth-child(even) { background: #f9fafb; }
        .summary { margin-top: 20px; background: #f3f4f6; padding: 12px; border-radius: 4px; }
        .summary table { width: 100%; }
        .summary td { padding: 4px 8px; }
        .footer { margin-top: 30px; display: flex; justify-content: space-between; }
        .signature-box { border-top: 1px solid #333; padding-top: 5px; margin-top: 40px; width: 200px; }
        .signature-box p { margin: 0; font-size: 10px; }
        .badge { background: #dbeafe; color: #1e40af; padding: 2px 8px; border-radius: 12px; font-size: 9px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $client->company_name }}</h1>
        <p>Timesheet for {{ $timesheet->month_year->format('F Y') }}</p>
    </div>

    <div class="client-info">
        <table>
            <tr>
                <td><strong>Employee:</strong> {{ $user->full_name }}</td>
                <td><strong>Employee No:</strong> {{ $user->employee_number }}</td>
            </tr>
            <tr>
                <td><strong>Position:</strong> {{ $user->position ?? 'N/A' }}</td>
                <td><strong>Department:</strong> {{ $user->department ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td><strong>Client:</strong> {{ $client->company_name }}</td>
                <td><strong>Generated:</strong> {{ $generated_at }}</td>
            </tr>
        </table>
    </div>

    <table class="timesheet-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Day</th>
                <th>Project</th>
                <th>Task Description</th>
                <th style="text-align: right;">Hours</th>
            </tr>
        </thead>
        <tbody>
            @foreach($details->sortBy('work_date') as $detail)
                <tr>
                    <td>{{ $detail->work_date->format('d M Y') }}</td>
                    <td>{{ $detail->work_date->format('D') }}</td>
                    <td>{{ $detail->project->project_code ?? 'N/A' }}</td>
                    <td>{{ $detail->task_description ?? '-' }}</td>
                    <td style="text-align: right;">{{ number_format($detail->hours_worked, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <table>
            <tr>
                <td><strong>Total Hours Worked:</strong></td>
                <td style="text-align: right;">{{ number_format($details->sum('hours_worked'), 2) }}</td>
            </tr>
            <tr>
                <td><strong>Total Days:</strong></td>
                <td style="text-align: right;">{{ $details->unique('work_date')->count() }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <div>
            <div class="signature-box">
                <p>Employee Signature</p>
                <p style="margin-top: 20px;">{{ $user->full_name }}</p>
            </div>
        </div>
        <div>
            <div class="signature-box">
                <p>Client Approval</p>
                <p style="margin-top: 20px;">_________________________</p>
            </div>
        </div>
    </div>

    <div style="text-align: center; margin-top: 30px; font-size: 9px; color: #999;">
        This timesheet was generated by NKS Capital EMS on {{ $generated_at }}
    </div>
</body>
</html>